package com.abc.rule.family.ipm

import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.builder.FGRootRecordBuilder;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.ops.builder.RecordRelationOpsBuilder;
import cho.carbon.rrc.record.FGRootRecord;
import cho.carbon.ops.builder.RecordRelationOpsBuilder;
import cho.carbon.sysdate.SystemDateTimeManager;
import cho.carbon.relation.RecordRelation;
import cho.carbon.relation.RelationCorrelation;
import cho.carbon.biz.constant.item.DXJDE2038Item;
import cho.carbon.biz.constant.EnumKeyValue;
import cho.carbon.biz.constant.RelationType;
import cho.carbon.biz.algorithm.CommonAlgorithm;
import cho.carbon.biz.common.CommonCalculation;

global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List recordRelationOpsBuilderNew;
global java.util.List rootRecordList;
global java.util.List attributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global cho.carbon.rrc.record.FGRootRecord fgRootRecord;
global  cho.carbon.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;

rule "设置户籍家庭人口数"
	salience 10 
when
	FuseAttribute(name==DXJDE2038Item.基本信息_家庭分类, CommonCalculation.isBasicLawful((String)getValue(AttributeValueType.STRING)), (Integer)getValue(AttributeValueType.INT) == EnumKeyValue.ENUM_家庭分类_户籍家庭);
then
	//户主数量和成员数量
	Integer hzCount = CommonAlgorithm.getAppointRecordRelationCount(recordComplexus, recordName, recordCode, RelationType.RR_家庭信息_户主_人口信息);
	Integer cyCount = CommonAlgorithm.getAppointRecordRelationCount(recordComplexus, recordName, recordCode, RelationType.RR_家庭信息_成员_人口信息);

	//设置户籍家庭人口数量
	FGAttribute peopleCount=FuseAttributeFactory.buildAttribute(DXJDE2038Item.基本信息_家庭人口数, hzCount+cyCount);
	attributeList.add(peopleCount);
end

rule "设置居住家庭人口数"
	salience 10 
when
	FuseAttribute(name==DXJDE2038Item.基本信息_家庭分类, CommonCalculation.isBasicLawful((String)getValue(AttributeValueType.STRING)), (Integer)getValue(AttributeValueType.INT) == EnumKeyValue.ENUM_家庭分类_居住家庭);
then 
	//居住成员数量
	Integer jzCount = CommonAlgorithm.getAppointRecordRelationCount(recordComplexus, recordName, recordCode, RelationType.RR_家庭信息_居住成员_人口信息);
	//设置居住家庭人口数量
	FGAttribute peopleCount=FuseAttributeFactory.buildAttribute(DXJDE2038Item.基本信息_家庭人口数, jzCount);
	attributeList.add(peopleCount);
end