package cho.carbon.biz.rule.dxjde2038.imp

import cho.carbon.relation.RelationCorrelation;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.relation.RecordRelation;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.fuse.improve.attribute.leaf.OpsLeafAttribute;
import cho.carbon.biz.constant.EnumKeyValue;
import cho.carbon.biz.common.CommonCalculation;
import cho.carbon.message.MessageFactory;
import cho.carbon.biz.constant.item.DXJDE2038Item;
import cho.carbon.fuse.improve.attribute.leaf.FuseLeafAttribute;
import cho.carbon.biz.constant.RelationType;
import cho.carbon.biz.algorithm.CommonAlgorithm;
import cho.carbon.model.uid.UidManager;

global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List recordRelationOpsBuilderNew;
global java.util.List rootRecordList;
global java.util.List attributeList;
global java.util.List addedLeafAttrList;
global java.util.List messageList;
global java.util.Map removedLeafAttrMap;
global cho.carbon.rrc.record.FGRootRecord fgRootRecord;
global cho.carbon.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;


rule "清空人口错误"
	salience 7
when
   $fa: FuseLeafAttribute(name==DXJDE2038Item.错误信息_错误类型);
then  
	removedLeafAttrMap.put($fa.getLeafCode(), $fa.getName());
end 

rule "户籍家庭没有户主"
	salience 6
when
	FuseAttribute( name==DXJDE2038Item.基本信息_家庭分类, CommonCalculation.isBasicLawful(getValue(AttributeValueType.STRING)), (Integer)getValue(AttributeValueType.INT)==EnumKeyValue.ENUM_家庭分类_户籍家庭)
then 
	//户主数量
	Integer hzCount = CommonAlgorithm.getAppointRecordRelationCount(recordComplexus, recordName, recordCode, RelationType.RR_家庭信息_户主_人口信息);
	if(hzCount != 1) {
	
		String code = UidManager.getUID(DXJDE2038Item.家庭信息_错误信息);
	
		FuseLeafAttribute leafAttr = FuseAttributeFactory.buildFuseLeafAttribute(recordCode, DXJDE2038Item.家庭信息_错误信息, code, DXJDE2038Item.错误信息_错误类型, EnumKeyValue.ENUM_家庭信息错误_户主数量错误);
		addedLeafAttrList.add(leafAttr);
		FuseLeafAttribute leafAttr2 = FuseAttributeFactory.buildFuseLeafAttribute(recordCode, DXJDE2038Item.家庭信息_错误信息, code, DXJDE2038Item.错误信息_描述, "家庭户主数量非一");
		addedLeafAttrList.add(leafAttr2);
	}
end

