package com.abc.rule.family.postimp

import cho.carbon.meta.enun.AttributeValueType;
import cho.carbon.fuse.improve.attribute.FuseAttributeFactory;
import cho.carbon.rrc.builder.FGRootRecordBuilder;
import cho.carbon.fuse.improve.attribute.OpsAttribute;
import cho.carbon.rrc.record.FGAttribute;
import cho.carbon.fuse.improve.attribute.FuseAttribute;
import cho.carbon.ops.builder.RecordRelationOpsBuilder;
import cho.carbon.rrc.record.FGRootRecord;
import cho.carbon.ops.builder.RecordRelationOpsBuilder;
import cho.carbon.sysdate.SystemDateTimeManager;
import cho.carbon.relation.RecordRelation;
import cho.carbon.relation.RelationCorrelation;


global java.lang.String hostCode; 
global java.lang.String hostType;

global java.lang.String userCode;
global java.lang.String recordCode;
global java.lang.String recordName;

global java.util.List recordRelationOpsBuilderNew;
global java.util.List rootRecordList;
global java.util.List attributeList;
global java.util.List addedLeafAttrList;
global java.util.Map removedLeafAttrMap;
global cho.carbon.rrc.record.FGRootRecord fgRootRecord;
global  cho.carbon.ops.builder.RecordRelationOpsBuilder recordRelationOpsBuilder;
global cho.carbon.complexus.FGRecordComplexus recordComplexus;

/*
rule "清空家庭错误"
	salience 7
when
   $fa: FuseLeafAttribute(name==FamilyItem.家庭错误信息_错误类型);
then  
	removedLeafAttrMap.put($fa.getLeafCode(), $fa.getName());
end 

rule "家庭没有户主"
	salience 6
when
	$value :FuseAttribute( name==FamilyItem.户籍地址)
	FuseAttribute( name==FamilyItem.家庭分类, (Integer)getValue(ValueType.INT)==EnumKeyValue.ENUM_家庭分类_户籍家庭)
 	not RecordRelation(type == RelationType.RR_家庭信息_户主_人口信息);
then 
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_错误类型, EnumKeyValue.ENUM_错误类型_家庭信息错误);
	addedLeafAttrList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_描述, "家庭没有户主");
	addedLeafAttrList.add(leafAttr2);
	
end

rule "家庭有户主但是和户主关系不是户主"
	salience 6
when
	FuseAttribute( name==FamilyItem.家庭分类, getValue(ValueType.INT)==EnumKeyValue.ENUM_家庭分类_户籍家庭)
	$value :FuseAttribute( name==FamilyItem.户籍地址 )
 	 RecordRelation(type == RelationType.RR_家庭信息_户主_人口信息, $huzCode:right);
 	 eval(recordComplexus.getRootRecord($huzCode) != null)
 	 eval( recordComplexus.getRootRecord($huzCode).findAttribute(PeopleItem.和户主关系) !=null)
 	 eval(!String.valueOf(EnumKeyValue.ENUM_和户主关系_户主).equals(String.valueOf(recordComplexus.getRootRecord($huzCode).findAttribute(PeopleItem.和户主关系).getValue(ValueType.STRING))) )
then 
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_错误类型, EnumKeyValue.ENUM_错误类型_家庭信息错误);
	addedLeafAttrList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_描述, "家庭有户主但是和户主关系不是户主");
	addedLeafAttrList.add(leafAttr2);
end

rule "家庭中户主大于一个"
	salience 6
when
	FuseAttribute( name==FamilyItem.家庭分类, getValue(ValueType.INT)==EnumKeyValue.ENUM_家庭分类_户籍家庭)
	$value :FuseAttribute( name==FamilyItem.户籍地址 )
 	RecordRelation(type == RelationType.RR_家庭信息_户主_人口信息, $left:left);
 	eval(DataIntrospection.getHzCount(recordComplexus, recordName, $left)>1 )
then 
	String code = CodeManager.newCode32();
	FuseLeafAttribute leafAttr = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_错误类型, EnumKeyValue.ENUM_错误类型_家庭信息错误);
	addedLeafAttrList.add(leafAttr);
	FuseLeafAttribute leafAttr2 = FuseLeafAttrFactory.newInstance($value.getCode(), FamilyItem.家庭错误信息, code, FamilyItem.家庭错误信息_描述, "家庭中户主大于一个");
	addedLeafAttrList.add(leafAttr2);
end

*/